name: faramove
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.1.3
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.1
  assorted_layout_widgets: ^7.0.0
  cached_network_image: ^3.2.3
  audio_video_progress_bar: ^1.0.0
  just_audio: ^0.9.31
  just_audio_background: ^0.0.1-beta.9
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/

 
